<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CommunityAbp.ProgressiveDelivery</RootNamespace>
    <Description>Application contracts (DTOs, application service interfaces, permissions) for CommunityAbp.ProgressiveDelivery.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunityAbp.ProgressiveDelivery.Domain.Shared\CommunityAbp.ProgressiveDelivery.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
    <PackageReference Include="Volo.Abp.Authorization.Abstractions" />
  </ItemGroup>

</Project>
