<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CommunityAbp.ProgressiveDelivery</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CommunityAbp.ProgressiveDelivery.Application\CommunityAbp.ProgressiveDelivery.Application.csproj" />
    <ProjectReference Include="..\CommunityAbp.ProgressiveDelivery.EntityFrameworkCore.Tests\CommunityAbp.ProgressiveDelivery.EntityFrameworkCore.Tests.csproj" />
  </ItemGroup>

</Project>
