namespace CommunityAbp.ProgressiveDelivery.EntityFrameworkCore;

public abstract class ProgressiveDeliveryEntityFrameworkCoreTestBase : ProgressiveDeliveryTestBase<ProgressiveDeliveryEntityFrameworkCoreTestModule>
{
}
